### ISSUE TITLE
Blurry Editor Text in the Metro UI

### ISSUE THREAD

**Issue by iAmANoobProgrammer** [casperb123/SynapseXUI#7]
The text in the editor is blurry on the metro ui, but on the normal synapse it's fine. I put 2 screenshots for comparison https://imgur.com/a/ZJ3xysh

**Comment by casperb123** [comment]
The problem is that i can't replicate this issue. On my computer the text isn't blurry on my ui. So I have no idea why it looks blurry on your computer.

Here is screenshots from my computer:
![metro](https://user-images.githubusercontent.com/42714453/150287551-9b624afc-a483-4254-a7be-0456c903341d.png)
![official](https://user-images.githubusercontent.com/42714453/150287554-ef56ac02-3ce9-4f4f-a264-eaf2419e7f73.png)

**Comment by iAmANoobProgrammer** [comment]
Oh well thanks for replying at least
